steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/dldaisy-project/mnist_train:$COMMIT_SHA",
        "-t",
        "gcr.io/dldaisy-project/mnist_train:latest",
        "${_CODE_PATH}/train",
      ]
    id: "MnistBuildImages"

  - name: "python:3.7-slim"
    entrypoint: "/bin/sh"
    args: [
        "-c",
        "cd ${_CODE_PATH};
        pip3 install cffi==1.12.3 --upgrade;
        pip3 install kfp==0.1.37;
        python pipeline.py --commit_id $COMMIT_SHA;
        cp pipeline.py.zip /workspace/pipeline.zip",
      ]
    id: "MnistPackagePipeline"

  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "/workspace/pipeline.zip",
        "gs://test-pipeline-version/$COMMIT_SHA/pipeline.zip"
      ]
    id: "MnistUploadPipeline"
    waitFor: ["MnistPackagePipeline"]

  - name: "gcr.io/jingzhangjz-experiment/ubuntu-curl"
    args: ["bash", "./mnist/curl.bash", "$COMMIT_SHA", "$_PIPELINE_ID"]
    id: "CreatePipelineVersionAndRun"

images:
  - "gcr.io/dldaisy-project/mnist_train:$COMMIT_SHA"
  - "gcr.io/dldaisy-project/mnist_train:latest"

substitutions:
  _CODE_PATH: /workspace/mnist
  _NAMESPACE: kubeflow
  _PIPELINE_ID: cb5b84f6-d11b-49b1-a084-93d43a53cd34
