steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_GCR_PATH}/kaggle_download:$COMMIT_SHA",
        "${_CODE_PATH}/download_dataset",
        "-f",
        "${_CODE_PATH}/download_dataset/Dockerfile",
      ]
    id: "BuildDownloadDataImage"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_GCR_PATH}/kaggle_visualize:$COMMIT_SHA",
        "${_CODE_PATH}/visualize_table",
        "-f",
        "${_CODE_PATH}/visualize_table/Dockerfile",
      ]
    id: "BuildVisualizeDataImage"

  - name: "python:3.7-slim"
    entrypoint: "/bin/sh"
    args: [
        "-c",
        "cd ${_CODE_PATH};
        pip3 install cffi==1.12.3 --upgrade;
        pip3 install kfp==0.1.37;
        python pipeline.py;
        cp pipeline.py.zip /workspace/pipeline.zip",
      ]
    id: "KagglePackagePipeline"

  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "/workspace/pipeline.zip",
        "gs://${_GS_BUCKET}/$COMMIT_SHA/pipeline.zip"
      ]
    id: "KaggleUploadPipeline"
    waitFor: ["MnistPackagePipeline"]


  - name: "gcr.io/cloud-builders/kubectl"
    entrypoint: "/bin/sh"
    args: [
        "-c",
        "cd ${_CODE_PATH};
        apt-get update;
        apt-get install -y python3-pip;
        apt-get install -y libssl-dev libffi-dev;
        /builder/kubectl.bash;
        pip3 install kfp==0.1.38;
        pip3 install kubernetes;
        python3 create_pipeline_version_and_run.py 
        --package_url https://storage.googleapis.com/${_GS_BUCKET}/$COMMIT_SHA/pipeline.zip
        --pipeline_id ${_PIPELINE_ID} 
        --version_name $COMMIT_SHA"
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=v38"
    id: "KaggleCreatePipelineVersionAndRun"

images:
  - "${_GCR_PATH}/kaggle_download:$COMMIT_SHA"
  - "${_GCR_PATH}/kaggle_visualize:$COMMIT_SHA"

substitutions:
  _CODE_PATH: /workspace/kaggle
  _NAMESPACE: kubeflow
  _GCR_PATH: gcr.io/dldaisy-project
  _GS_BUCKET: dldaisy-kaggle
  _PIPELINE_ID: 51b8101f-4496-4379-a879-8a0753bd8844